package cz.lukynka.prettylog.style

data class LogStyle(val textColor: AnsiColor, val backgroundColor: AnsiColor? = null) {

    companion object {
        val BLACK = LogStyle(AnsiColor.BLACK, null)
        val RED = LogStyle(AnsiColor.RED, null)
        val GREEN = LogStyle(AnsiColor.GREEN, null)
        val YELLOW = LogStyle(AnsiColor.YELLOW, null)
        val BLUE = LogStyle(AnsiColor.BLUE, null)
        val PURPLE = LogStyle(AnsiColor.PURPLE, null)
        val CYAN = LogStyle(AnsiColor.CYAN, null)
        val WHITE = LogStyle(AnsiColor.WHITE, null)
        val BRIGHT_BLACK = LogStyle(AnsiColor.BRIGHT_BLACK, null)
        val BRIGHT_RED = LogStyle(AnsiColor.BRIGHT_RED, null)
        val BRIGHT_GREEN = LogStyle(AnsiColor.BRIGHT_GREEN, null)
        val BRIGHT_YELLOW = LogStyle(AnsiColor.BRIGHT_YELLOW, null)
        val BRIGHT_BLUE = LogStyle(AnsiColor.BRIGHT_BLUE, null)
        val BRIGHT_PURPLE = LogStyle(AnsiColor.BRIGHT_PURPLE, null)
        val BRIGHT_CYAN = LogStyle(AnsiColor.BRIGHT_CYAN, null)
        val BRIGHT_WHITE = LogStyle(AnsiColor.BRIGHT_WHITE, null)
        val GRAY = LogStyle(AnsiColor.GRAY, null)
        val ORANGE = LogStyle(AnsiColor.ORANGE, null)
        val PINK = LogStyle(AnsiColor.PINK, null)
        val CUTE_PINK = LogStyle(AnsiColor.CUTE_PINK, null)
        val AQUA = LogStyle(AnsiColor.AQUA, null)
        val GOLD = LogStyle(AnsiColor.GOLD, null)
        val LIGHT_GREEN = LogStyle(AnsiColor.LIGHT_GREEN, null)
        val LIGHT_BLUE = LogStyle(AnsiColor.LIGHT_BLUE, null)
        val MAGENTA = LogStyle(AnsiColor.MAGENTA, null)
        val LIGHT_CYAN = LogStyle(AnsiColor.LIGHT_CYAN, null)
        val LIGHT_GRAY = LogStyle(AnsiColor.LIGHT_GRAY, null)
        val DARK_RED = LogStyle(AnsiColor.DARK_RED, null)
        val DARK_GREEN = LogStyle(AnsiColor.DARK_GREEN, null)
        val DARK_BLUE = LogStyle(AnsiColor.DARK_BLUE, null)
        val DARK_YELLOW = LogStyle(AnsiColor.DARK_YELLOW, null)
        val DARK_PURPLE = LogStyle(AnsiColor.DARK_PURPLE, null)

        val FILLED_BLACK = LogStyle(AnsiColor.WHITE, AnsiColor.BLACK_BACKGROUND)
        val FILLED_RED = LogStyle(AnsiColor.BLACK, AnsiColor.RED_BACKGROUND)
        val FILLED_GREEN = LogStyle(AnsiColor.BLACK, AnsiColor.GREEN_BACKGROUND)
        val FILLED_YELLOW = LogStyle(AnsiColor.BLACK, AnsiColor.YELLOW_BACKGROUND)
        val FILLED_BLUE = LogStyle(AnsiColor.BLACK, AnsiColor.BLUE_BACKGROUND)
        val FILLED_PURPLE = LogStyle(AnsiColor.BLACK, AnsiColor.PURPLE_BACKGROUND)
        val FILLED_CYAN = LogStyle(AnsiColor.BLACK, AnsiColor.CYAN_BACKGROUND)
        val FILLED_WHITE = LogStyle(AnsiColor.BLACK, AnsiColor.WHITE_BACKGROUND)
        val FILLED_BRIGHT_BLACK = LogStyle(AnsiColor.WHITE, AnsiColor.BRIGHT_BLACK_BACKGROUND)
        val FILLED_BRIGHT_RED = LogStyle(AnsiColor.BLACK, AnsiColor.BRIGHT_RED_BACKGROUND)
        val FILLED_BRIGHT_GREEN = LogStyle(AnsiColor.BLACK, AnsiColor.BRIGHT_GREEN_BACKGROUND)
        val FILLED_BRIGHT_YELLOW = LogStyle(AnsiColor.BLACK, AnsiColor.BRIGHT_YELLOW_BACKGROUND)
        val FILLED_BRIGHT_BLUE = LogStyle(AnsiColor.BLACK, AnsiColor.BRIGHT_BLUE_BACKGROUND)
        val FILLED_BRIGHT_PURPLE = LogStyle(AnsiColor.BLACK, AnsiColor.BRIGHT_PURPLE_BACKGROUND)
        val FILLED_BRIGHT_CYAN = LogStyle(AnsiColor.BLACK, AnsiColor.BRIGHT_CYAN_BACKGROUND)
        val FILLED_BRIGHT_WHITE = LogStyle(AnsiColor.BLACK, AnsiColor.BRIGHT_WHITE_BACKGROUND)
        val FILLED_GRAY = LogStyle(AnsiColor.BLACK, AnsiColor.GRAY_BACKGROUND)
        val FILLED_ORANGE = LogStyle(AnsiColor.BLACK, AnsiColor.ORANGE_BACKGROUND)
        val FILLED_PINK = LogStyle(AnsiColor.BLACK, AnsiColor.PINK_BACKGROUND)
        val FILLED_CUTE_PINK = LogStyle(AnsiColor.BLACK, AnsiColor.CUTE_PINK_BACKGROUND)
        val FILLED_AQUA = LogStyle(AnsiColor.BLACK, AnsiColor.AQUA_BACKGROUND)
        val FILLED_GOLD = LogStyle(AnsiColor.BLACK, AnsiColor.GOLD_BACKGROUND)
        val FILLED_LIGHT_GREEN = LogStyle(AnsiColor.BLACK, AnsiColor.LIGHT_GREEN_BACKGROUND)
        val FILLED_LIGHT_BLUE = LogStyle(AnsiColor.BLACK, AnsiColor.LIGHT_BLUE_BACKGROUND)
        val FILLED_MAGENTA = LogStyle(AnsiColor.BLACK, AnsiColor.MAGENTA_BACKGROUND)
        val FILLED_LIGHT_CYAN = LogStyle(AnsiColor.BLACK, AnsiColor.LIGHT_CYAN_BACKGROUND)
        val FILLED_LIGHT_GRAY = LogStyle(AnsiColor.BLACK, AnsiColor.LIGHT_GRAY_BACKGROUND)
        val FILLED_DARK_RED = LogStyle(AnsiColor.BLACK, AnsiColor.DARK_RED_BACKGROUND)
        val FILLED_DARK_GREEN = LogStyle(AnsiColor.WHITE, AnsiColor.DARK_GREEN_BACKGROUND)
        val FILLED_DARK_BLUE = LogStyle(AnsiColor.WHITE, AnsiColor.DARK_BLUE_BACKGROUND)
        val FILLED_DARK_YELLOW = LogStyle(AnsiColor.WHITE, AnsiColor.DARK_YELLOW_BACKGROUND)
        val FILLED_DARK_PURPLE = LogStyle(AnsiColor.BLACK, AnsiColor.DARK_PURPLE_BACKGROUND)
    }
}